name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2.3.1
        with:
          python-version: "3.8"
      - name: Install tools using pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip nox nox-poetry poetry
      - name: Run test suite using Nox
        run: nox --force-color
      - name: Build documentation to check for build errors
        run: nox -s build-docs -- deploy X.X.X
